### ISSUE TITLE
Unable to install due to missing gson bundle

### ISSUE THREAD

**Issue by rombert** [devsprint/org.eclipse.mylyn.github#10]
The connector can no longer be installed without checking 'Contact all update sites'. Of course, it works with the setting enabled, but:
- it takes longer
- it will not work with 'discovery' UIs such as the Mylyn connector discovery or the Eclipse marketplace.

The exact p2 error is:

```
 Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn GitHub Feature 0.2.2.201102282326 (org.eclipse.mylyn.github.feature.feature.group 0.2.2.201102282326)
  Missing requirement: Mylyn GitHub Core Plug-in 0.2.2.201102282326 (org.eclipse.mylyn.github.core 0.2.2.201102282326) requires 'bundle com.google.gson 1.6.0'    but it could not be found
  Cannot satisfy dependency:
    From: Mylyn GitHub Feature 0.2.2.201102282326 (org.eclipse.mylyn.github.feature.feature.group 0.2.2.201102282326)
    To: org.eclipse.mylyn.github.core [0.2.2.201102282326]
```

**Comment by thoutbeckers** [comment]
The workaround I currently use is to install the gson dependency by hand (see wiki for a link to the bundle), and to change the commons logging bundle from 1.1.1 to 1.0.4. (not sure if the latter comes with Eclipse or it from some other project).

I can not use "Contact all update sites" because (as with a lot of other people) this gives weird dependency errors for other things installed.

**Comment by rombert** [comment]
That's quite an effort. I guess that the feature.xml should include a plugin entry for the gson bundle.

**Comment by thoutbeckers** [comment]
Yes, just documenting what I did for people for whom the 'Contact all update sites' workaround does not work.

**Comment by devsprint** [comment]
quite interesting... I haven't seen the problem last night when I have tested, but I guess was because I already had it installed on my usual test machine. However, the manifest of core plug-in has a reference to gson and re-export gson to the other plug-ins.  The suggested change to update feature.xml is the proper way to fix it?

**Comment by devsprint** [comment]
if you run a build using maven, it is not complaining on building the feature or creating the update-site artefacts. However, I was able to find a post regarding consuming Orbit bundles...
http://wiki.eclipse.org/Easy_Bake_Builds_with_Orbit_Bundles
but, still I will take a look to tycho too...

**Comment by rombert** [comment]
The tycho build does not complain since the dependencies are available locally. The way they are resolved at installation time is a different concern.

The simplest way to solve this is to include the plugin in the feature. Here's [an example of what I did for ereviewboard](https://github.com/rombert/ereviewboard/blob/master/org.review_board.ereviewboard/feature.xml#L120)..

**Comment by thoutbeckers** [comment]
I (as you noticed) created a pull request for that. Sadly GitHub won't let you add pull requests to an issue (though in my feature request they said this is a high priority)

**Comment by devsprint** [comment]
fixed the problem.
https://github.com/devsprint/org.eclipse.mylyn.github/commit/d7d3506ed43ddfd7166b8775b2153cba2249187c
